ALTER TYPE "app"."DataFieldType" ADD VALUE IF NOT EXISTS 'LOOKUP';
ALTER TYPE "app"."DataFieldType" ADD VALUE IF NOT EXISTS 'ROLLUP';
ALTER TYPE "app"."DataFieldType" ADD VALUE IF NOT EXISTS 'FORMULA';
