export interface PermissionCatalogEntry {
  code: string;
  module: string;
  resource: string;
  action: string;
  description: string;
  isSensitive?: boolean;
}

export const PERMISSIONS = {
  USER_READ: 'user.read',
  USER_CREATE: 'user.create',
  USER_UPDATE: 'user.update',
  USER_DISABLE: 'user.disable',
  ROLE_READ: 'role.read',
  ROLE_CREATE: 'role.create',
  ROLE_UPDATE: 'role.update',
  ROLE_ASSIGN: 'role.assign',
  EMPLOYEE_READ: 'employee.read',
  EMPLOYEE_UPDATE: 'employee.update',
  EMPLOYEE_ARCHIVE: 'employee.archive',
  EMPLOYEE_DELETE: 'employee.delete',
  PROJECT_READ: 'project.read',
  PROJECT_CREATE: 'project.create',
  PROJECT_UPDATE: 'project.update',
  PROJECT_DELETE: 'project.delete',
  PROJECT_PROGRESS_PUBLISH: 'project.progress.publish',
  TASK_READ: 'task.read',
  TASK_CREATE: 'task.create',
  TASK_UPDATE: 'task.update',
  TASK_DELETE: 'task.delete',
  DOCUMENT_READ: 'document.read',
  DOCUMENT_CREATE: 'document.create',
  DOCUMENT_UPDATE: 'document.update',
  DOCUMENT_SHARE: 'document.share',
  DOCUMENT_DELETE: 'document.delete',
  MEETING_READ: 'meeting.read',
  MEETING_CREATE: 'meeting.create',
  MEETING_UPDATE: 'meeting.update',
  MEETING_DELETE: 'meeting.delete',
  DECISION_READ: 'decision.read',
  DECISION_CREATE: 'decision.create',
  DECISION_UPDATE: 'decision.update',
  DECISION_DELETE: 'decision.delete',
  ISSUE_READ: 'issue.read',
  ISSUE_CREATE: 'issue.create',
  ISSUE_UPDATE: 'issue.update',
  ISSUE_DELETE: 'issue.delete',
  RISK_READ: 'risk.read',
  RISK_CREATE: 'risk.create',
  RISK_UPDATE: 'risk.update',
  RISK_DELETE: 'risk.delete',
  PARTNER_READ: 'partner.read',
  PARTNER_CREATE: 'partner.create',
  PARTNER_UPDATE: 'partner.update',
  PARTNER_DELETE: 'partner.delete',
  BASE_READ: 'base.read',
  BASE_CREATE: 'base.create',
  BASE_UPDATE: 'base.update',
  BASE_DELETE: 'base.delete',
  SEARCH_READ: 'search.read',
  ACTIVITY_READ: 'activity.read',
  KNOWLEDGE_ADMIN: 'knowledge.admin',
  REPORT_READ: 'report.read',
  REPORT_EXPORT: 'report.export',
  GOVERNANCE_READ: 'governance.read',
  BACKUP_READ: 'backup.read',
  BACKUP_EXECUTE: 'backup.execute',
  RESTORE_EXECUTE: 'restore.execute',
  AUDIT_READ: 'audit.read',
  SYSTEM_CONFIGURE: 'system.configure',
  INTELLIGENCE_READ: 'intelligence.read',
  INTELLIGENCE_MANAGE: 'intelligence.manage',
  APPLICATION_READ: 'application.read',
  APPLICATION_MANAGE: 'application.manage',
  NON_PROJECT_RD_READ: 'nonProjectRd.read',
  NON_PROJECT_RD_MANAGE: 'nonProjectRd.manage',
  RESOURCE_READ: 'resource.read',
  RESOURCE_MANAGE: 'resource.manage',
  EXTENSION_READ: 'extension.read',
  EXTENSION_CONFIGURE: 'extension.configure',
} as const;

export type PermissionCode = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];

export const PERMISSION_CATALOG = [
  permission(PERMISSIONS.USER_READ, 'iam', 'user', 'read', 'View users'),
  permission(PERMISSIONS.USER_CREATE, 'iam', 'user', 'create', 'Create users', true),
  permission(PERMISSIONS.USER_UPDATE, 'iam', 'user', 'update', 'Update users', true),
  permission(PERMISSIONS.USER_DISABLE, 'iam', 'user', 'disable', 'Disable users', true),
  permission(PERMISSIONS.ROLE_READ, 'iam', 'role', 'read', 'View roles'),
  permission(PERMISSIONS.ROLE_CREATE, 'iam', 'role', 'create', 'Create roles', true),
  permission(PERMISSIONS.ROLE_UPDATE, 'iam', 'role', 'update', 'Update roles', true),
  permission(PERMISSIONS.ROLE_ASSIGN, 'iam', 'role', 'assign', 'Assign roles', true),
  permission(PERMISSIONS.EMPLOYEE_READ, 'employees', 'employee', 'read', 'View employees'),
  permission(PERMISSIONS.EMPLOYEE_UPDATE, 'employees', 'employee', 'update', 'Update employees'),
  permission(
    PERMISSIONS.EMPLOYEE_ARCHIVE,
    'employees',
    'employee',
    'archive',
    'Archive employees',
    true,
  ),
  permission(
    PERMISSIONS.EMPLOYEE_DELETE,
    'employees',
    'employee',
    'delete',
    'Delete employees',
    true,
  ),
  permission(PERMISSIONS.PROJECT_READ, 'projects', 'project', 'read', 'View projects'),
  permission(PERMISSIONS.PROJECT_CREATE, 'projects', 'project', 'create', 'Create projects'),
  permission(PERMISSIONS.PROJECT_UPDATE, 'projects', 'project', 'update', 'Update projects'),
  permission(PERMISSIONS.PROJECT_DELETE, 'projects', 'project', 'delete', 'Delete projects', true),
  permission(
    PERMISSIONS.PROJECT_PROGRESS_PUBLISH,
    'projects',
    'project_progress',
    'publish',
    'Adopt or ignore project progress drafts',
    true,
  ),
  permission(PERMISSIONS.TASK_READ, 'tasks', 'task', 'read', 'View tasks'),
  permission(PERMISSIONS.TASK_CREATE, 'tasks', 'task', 'create', 'Create tasks'),
  permission(PERMISSIONS.TASK_UPDATE, 'tasks', 'task', 'update', 'Update tasks'),
  permission(PERMISSIONS.TASK_DELETE, 'tasks', 'task', 'delete', 'Delete tasks', true),
  permission(PERMISSIONS.DOCUMENT_READ, 'content', 'document', 'read', 'View documents'),
  permission(PERMISSIONS.DOCUMENT_CREATE, 'content', 'document', 'create', 'Create documents'),
  permission(PERMISSIONS.DOCUMENT_UPDATE, 'content', 'document', 'update', 'Update documents'),
  permission(PERMISSIONS.DOCUMENT_SHARE, 'content', 'document', 'share', 'Share documents', true),
  permission(PERMISSIONS.DOCUMENT_DELETE, 'content', 'document', 'delete', 'Delete documents', true),
  permission(PERMISSIONS.MEETING_READ, 'management', 'meeting', 'read', 'View meetings'),
  permission(PERMISSIONS.MEETING_CREATE, 'management', 'meeting', 'create', 'Create meetings'),
  permission(PERMISSIONS.MEETING_UPDATE, 'management', 'meeting', 'update', 'Update meetings'),
  permission(PERMISSIONS.MEETING_DELETE, 'management', 'meeting', 'delete', 'Delete meetings', true),
  permission(PERMISSIONS.DECISION_READ, 'management', 'decision', 'read', 'View decisions'),
  permission(PERMISSIONS.DECISION_CREATE, 'management', 'decision', 'create', 'Create decisions'),
  permission(PERMISSIONS.DECISION_UPDATE, 'management', 'decision', 'update', 'Update decisions'),
  permission(PERMISSIONS.DECISION_DELETE, 'management', 'decision', 'delete', 'Delete decisions', true),
  permission(PERMISSIONS.ISSUE_READ, 'management', 'issue', 'read', 'View issues'),
  permission(PERMISSIONS.ISSUE_CREATE, 'management', 'issue', 'create', 'Create issues'),
  permission(PERMISSIONS.ISSUE_UPDATE, 'management', 'issue', 'update', 'Update issues'),
  permission(PERMISSIONS.ISSUE_DELETE, 'management', 'issue', 'delete', 'Delete issues', true),
  permission(PERMISSIONS.RISK_READ, 'management', 'risk', 'read', 'View risks'),
  permission(PERMISSIONS.RISK_CREATE, 'management', 'risk', 'create', 'Create risks'),
  permission(PERMISSIONS.RISK_UPDATE, 'management', 'risk', 'update', 'Update risks'),
  permission(PERMISSIONS.RISK_DELETE, 'management', 'risk', 'delete', 'Delete risks', true),
  permission(PERMISSIONS.PARTNER_READ, 'management', 'partner', 'read', 'View partners'),
  permission(PERMISSIONS.PARTNER_CREATE, 'management', 'partner', 'create', 'Create partners'),
  permission(PERMISSIONS.PARTNER_UPDATE, 'management', 'partner', 'update', 'Update partners'),
  permission(PERMISSIONS.PARTNER_DELETE, 'management', 'partner', 'delete', 'Delete partners', true),
  permission(PERMISSIONS.BASE_READ, 'base', 'base', 'read', 'View Base workspaces and records'),
  permission(PERMISSIONS.BASE_CREATE, 'base', 'base', 'create', 'Create Base workspaces and records'),
  permission(PERMISSIONS.BASE_UPDATE, 'base', 'base', 'update', 'Update Base workspaces and records'),
  permission(PERMISSIONS.BASE_DELETE, 'base', 'base', 'delete', 'Delete Base workspaces and records', true),
  permission(PERMISSIONS.SEARCH_READ, 'search', 'search', 'read', 'Use global search'),
  permission(PERMISSIONS.ACTIVITY_READ, 'activity', 'activity', 'read', 'View activity timelines'),
  permission(PERMISSIONS.KNOWLEDGE_ADMIN, 'knowledge', 'knowledge', 'admin', 'Manage knowledge index and health', true),
  permission(PERMISSIONS.REPORT_READ, 'reporting', 'report', 'read', 'View reports'),
  permission(PERMISSIONS.REPORT_EXPORT, 'reporting', 'report', 'export', 'Export reports', true),
  permission(PERMISSIONS.GOVERNANCE_READ, 'governance', 'governance', 'read', 'View governance health and backup status'),
  permission(PERMISSIONS.BACKUP_READ, 'governance', 'backup', 'read', 'View backups'),
  permission(
    PERMISSIONS.BACKUP_EXECUTE,
    'governance',
    'backup',
    'execute',
    'Execute backups',
    true,
  ),
  permission(
    PERMISSIONS.RESTORE_EXECUTE,
    'governance',
    'restore',
    'execute',
    'Execute restores',
    true,
  ),
  permission(PERMISSIONS.AUDIT_READ, 'iam', 'audit', 'read', 'View security audits', true),
  permission(
    PERMISSIONS.SYSTEM_CONFIGURE,
    'system',
    'system',
    'configure',
    'Configure the system',
    true,
  ),
  permission(PERMISSIONS.INTELLIGENCE_READ, 'intelligence', 'intelligence', 'read', 'View intelligence catalog and items'),
  permission(PERMISSIONS.INTELLIGENCE_MANAGE, 'intelligence', 'intelligence', 'manage', 'Manage intelligence catalog and items', true),
  permission(PERMISSIONS.APPLICATION_READ, 'applications', 'application', 'read', 'View application cases and workflow templates'),
  permission(PERMISSIONS.APPLICATION_MANAGE, 'applications', 'application', 'manage', 'Manage application cases and workflow templates', true),
  permission(PERMISSIONS.NON_PROJECT_RD_READ, 'operations', 'nonProjectRd', 'read', 'View non-project R&D records'),
  permission(PERMISSIONS.NON_PROJECT_RD_MANAGE, 'operations', 'nonProjectRd', 'manage', 'Manage non-project R&D records'),
  permission(PERMISSIONS.RESOURCE_READ, 'operations', 'resource', 'read', 'View resource profiles and load'),
  permission(PERMISSIONS.RESOURCE_MANAGE, 'operations', 'resource', 'manage', 'Manage resource profiles and load'),
  permission(PERMISSIONS.EXTENSION_READ, 'extensions', 'extension', 'read', 'View extension profiles and runs'),
  permission(PERMISSIONS.EXTENSION_CONFIGURE, 'extensions', 'extension', 'configure', 'Configure extensions and credentials', true),
] as const satisfies readonly PermissionCatalogEntry[];

export const BUILT_IN_ROLES = {
  SUPER_ADMIN: {
    code: 'SUPER_ADMIN',
    name: '超级管理员',
    description: '拥有全部功能和数据权限的系统管理员',
  },
  EMPLOYEE: {
    code: 'EMPLOYEE',
    name: '普通员工',
    description: '访问本人创建、负责或参与的数据',
  },
} as const;

export const EMPLOYEE_DEFAULT_PERMISSION_CODES = new Set([
  'employee.read',
  'employee.update',
  'project.read',
  'project.create',
  'project.update',
  'task.read',
  'task.create',
  'task.update',
  'document.read',
  'document.create',
  'document.update',
  'meeting.read',
  'meeting.create',
  'meeting.update',
  'decision.read',
  'decision.create',
  'decision.update',
  'issue.read',
  'issue.create',
  'issue.update',
  'risk.read',
  'risk.create',
  'risk.update',
  'partner.read',
  'partner.create',
  'partner.update',
  'base.read',
  'base.create',
  'base.update',
  'search.read',
  'activity.read',
  'report.read',
  'intelligence.read',
  'application.read',
  'nonProjectRd.read',
  'nonProjectRd.manage',
  'resource.read',
  'resource.manage',
]);

function permission(
  code: string,
  module: string,
  resource: string,
  action: string,
  description: string,
  isSensitive = false,
): PermissionCatalogEntry {
  return { code, module, resource, action, description, isSensitive };
}
