export const ErrorCodes = {
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  REQUEST_CONTEXT_UNAVAILABLE: 'REQUEST_CONTEXT_UNAVAILABLE',
  DATABASE_ERROR: 'DATABASE_ERROR',
  PROJECT_CODE_EXISTS: 'PROJECT_CODE_EXISTS',
  PROJECT_NOT_FOUND: 'PROJECT_NOT_FOUND',
  MILESTONE_NOT_FOUND: 'MILESTONE_NOT_FOUND',
  MILESTONE_PROJECT_MISMATCH: 'MILESTONE_PROJECT_MISMATCH',
  TASK_NOT_FOUND: 'TASK_NOT_FOUND',
  TASK_INVALID_REFERENCE: 'TASK_INVALID_REFERENCE',
  TASK_DEPENDENCY_INCOMPLETE: 'TASK_DEPENDENCY_INCOMPLETE',
  TASK_DEPENDENCY_CYCLE: 'TASK_DEPENDENCY_CYCLE',
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];
