export const ErrorCodes = {
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  TENANT_CONTEXT_REQUIRED: 'TENANT_CONTEXT_REQUIRED',
  REQUEST_CONTEXT_UNAVAILABLE: 'REQUEST_CONTEXT_UNAVAILABLE',
  TENANT_SCHEMA_RESOLUTION_FAILED: 'TENANT_SCHEMA_RESOLUTION_FAILED',
  DATABASE_ERROR: 'DATABASE_ERROR',
  TENANT_KEY_ALREADY_EXISTS: 'TENANT_KEY_ALREADY_EXISTS',
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];
