import { HttpStatus, Injectable, Optional } from '@nestjs/common';
import { ContentDocumentType, FileAssetStatus, MeetingActionStatus, MeetingStatus, Prisma, TaskStatus } from '@prisma/client';
import { PlatformPrismaService } from '../../../../infrastructure/prisma/platform-prisma.service';
import { AppError } from '../../../../shared/errors/app-error';
import { ErrorCodes } from '../../../../shared/errors/error-codes';
import { TasksService } from '../../tasks/application/tasks.service';
import { ActivityService } from '../../activity/application/activity.service';
import { RequestContextService } from '../../../../infrastructure/context/request-context.service';
import { DataScopeService } from '../../../iam/application/data-scope.service';
import { CreateMeetingActionDto, CreateMeetingAgendaItemDto, CreateMeetingDto, CreateSourceTaskDto, ListMeetingsQueryDto, UpdateMeetingActionDto, UpdateMeetingDto } from '../interface/http/dto/management.dto';

function textBlock(type:string,text:string,attrs?:Prisma.InputJsonObject):Prisma.InputJsonObject{return{type,...(attrs?{attrs}:{}),content:[{type:'text',text}]};}
function meetingMinutesTemplate(minutes:string|null):Prisma.InputJsonObject{const legacyParagraphs=minutes!==null&&minutes.length>0?minutes.split(/\r?\n/).map(line=>line.length?textBlock('paragraph',line):{type:'paragraph'}):[{type:'paragraph'}];return{type:'doc',content:[textBlock('heading','会议要点',{level:2}),...legacyParagraphs,textBlock('heading','决策',{level:2}),{type:'paragraph'},textBlock('heading','行动项',{level:2}),{type:'paragraph'}]};}
function meetingMinutesPlainText(minutes:string|null){return['会议要点',...(minutes?[minutes]:[]),'决策','行动项'].join('\n');}

@Injectable()
export class MeetingsService {
  constructor(
    private readonly prisma:PlatformPrismaService,
    private readonly tasks:TasksService,
    private readonly requestContext: RequestContextService,
    private readonly dataScope: DataScopeService,
    @Optional() private readonly activities?: ActivityService,
  ){}
  async list(query:ListMeetingsQueryDto){const page=query.page??1,pageSize=Math.min(query.pageSize??20,100);const principal=this.requestContext.requirePrincipal();const scheduledAt:Prisma.DateTimeFilter={...(query.startFrom?{gte:new Date(query.startFrom)}:{}),...(query.startTo?{lte:new Date(query.startTo)}:{})};const where:Prisma.MeetingWhereInput={AND:[{archivedAt:null,...(query.projectId?{projectId:query.projectId}:{}),...(query.status?{status:query.status}:{}),...(query.startFrom||query.startTo?{scheduledAt}:{})},this.dataScope.meetings(principal)]};const[data,total]=await this.prisma.$transaction([this.prisma.meeting.findMany({where,orderBy:[{scheduledAt:'asc'}],skip:(page-1)*pageSize,take:pageSize}),this.prisma.meeting.count({where})]);return{data,meta:{page,pageSize,total}};}
  async get(id:string,now=new Date()){const principal=this.requestContext.requirePrincipal();const item=await this.prisma.meeting.findFirst({where:{AND:[{id,archivedAt:null},this.dataScope.meetings(principal)]},include:{actions:{where:{archivedAt:null},orderBy:{dueAt:'asc'},include:{tasks:{select:{id:true,status:true,dueAt:true,updatedAt:true}}}},agendaItems:{where:{archivedAt:null},orderBy:{sequence:'asc'}},decisions:{where:{archivedAt:null},orderBy:{updatedAt:'desc'}},minutesDocument:true,fileAssets:{where:{status:FileAssetStatus.ACTIVE},orderBy:{updatedAt:'desc'},include:{versions:{orderBy:{versionNumber:'desc'},take:1}}}}});if(!item)throw this.notFound(ErrorCodes.MEETING_NOT_FOUND,'Meeting not found');const{fileAssets,...meeting}=item;return{...meeting,actions:item.actions.map(({tasks:task,...action})=>{const effectiveDueAt=task?.dueAt??action.dueAt;const effectiveStatus=task?.status??action.status;return{...action,task,taskStatus:task?.status??null,effectiveDueAt,isOverdue:Boolean(effectiveDueAt&&effectiveDueAt.getTime()<now.getTime()&&!['DONE','CANCELLED'].includes(effectiveStatus))}}),attachments:fileAssets.map(({versions,...asset})=>({...asset,latestVersion:versions[0]??null}))};}
  async create(dto:CreateMeetingDto){const principal=this.requestContext.requirePrincipal();if(dto.projectId)await this.assertProject(dto.projectId);return this.prisma.meeting.create({data:{...dto,scheduledAt:new Date(dto.scheduledAt),heldAt:dto.heldAt?new Date(dto.heldAt):(dto.status===MeetingStatus.HELD?new Date():undefined),createdByUserId:principal.userId,updatedByUserId:principal.userId,organizerUserId:principal.userId}})}
  async update(id:string,dto:UpdateMeetingDto){const principal=this.requestContext.requirePrincipal();const old=await this.get(id);if(dto.projectId)await this.assertProject(dto.projectId);const status=dto.status??old.status;return this.prisma.meeting.update({where:{id},data:{...dto,scheduledAt:dto.scheduledAt?new Date(dto.scheduledAt):undefined,heldAt:status===MeetingStatus.HELD?(dto.heldAt?new Date(dto.heldAt):(old.heldAt??new Date())):null,updatedByUserId:principal.userId}})}
  async archive(id:string){return this.prisma.$transaction(async tx=>{const meeting=await tx.meeting.findFirst({where:{id,archivedAt:null}});if(!meeting)throw this.notFound(ErrorCodes.MEETING_NOT_FOUND,'Meeting not found');const open=await tx.meetingAction.count({where:{meetingId:id,archivedAt:null,status:{in:[MeetingActionStatus.OPEN,MeetingActionStatus.IN_PROGRESS]}}});if(open)throw new AppError({code:ErrorCodes.MEETING_HAS_OPEN_ACTIONS,message:'Meeting has open actions',statusCode:HttpStatus.CONFLICT});await tx.meeting.update({where:{id},data:{archivedAt:new Date()}});});}
  async createAction(meetingId:string,dto:CreateMeetingActionDto){const meeting=await this.get(meetingId);const action=await this.prisma.meetingAction.create({data:{meetingId,...dto,dueAt:dto.dueAt?new Date(dto.dueAt):undefined}});await this.activities?.append({actorKind:'HUMAN',objectType:'MEETING_ACTION',objectId:action.id,projectId:meeting.projectId,action:'CREATED',summary:`新增会议行动项：${action.title}`,sourcePath:`/meetings?meetingId=${encodeURIComponent(meetingId)}`});return action;}
  async updateAction(meetingId:string,id:string,dto:UpdateMeetingActionDto){return this.prisma.$transaction(async tx=>{const current=await tx.meetingAction.findFirst({where:{id,meetingId,archivedAt:null},include:{meeting:{select:{projectId:true}}}});if(!current)throw this.notFound(ErrorCodes.MEETING_ACTION_NOT_FOUND,'Meeting action not found');const{syncTask,...fields}=dto;const action=await tx.meetingAction.update({where:{id},data:{...fields,dueAt:dto.dueAt===null?null:dto.dueAt?new Date(dto.dueAt):undefined}});if(syncTask&&current.taskId){await tx.workTask.update({where:{id:current.taskId},data:{...(dto.ownerName!==undefined?{assigneeName:dto.ownerName}:{}),...(dto.dueAt!==undefined?{dueAt:dto.dueAt===null?null:new Date(dto.dueAt)}:{}),...(dto.status!==undefined?{status:this.taskStatusFromAction(dto.status),completionPercent:dto.status===MeetingActionStatus.DONE?100:undefined,completedAt:dto.status===MeetingActionStatus.DONE?new Date():dto.status===MeetingActionStatus.CANCELLED?null:undefined}:{})}});}await this.activities?.append({actorKind:'HUMAN',objectType:'MEETING_ACTION',objectId:id,projectId:current.meeting.projectId,action:'UPDATED',summary:`更新会议行动项：${action.title}`,sourcePath:`/meetings?meetingId=${encodeURIComponent(meetingId)}`,metadata:{syncTask:Boolean(syncTask)}},tx);return action;});}
  async archiveAction(meetingId:string,id:string){const result=await this.prisma.meetingAction.updateMany({where:{id,meetingId,archivedAt:null},data:{archivedAt:new Date()}});if(!result.count)throw this.notFound(ErrorCodes.MEETING_ACTION_NOT_FOUND,'Meeting action not found');}
  async createAgendaItem(meetingId:string,dto:CreateMeetingAgendaItemDto){return this.prisma.$transaction(tx=>this.createIntelligenceAgendaInTransaction(tx,meetingId,dto))}
  async createIntelligenceAgendaInTransaction(tx:Prisma.TransactionClient,meetingId:string,dto:CreateMeetingAgendaItemDto){const meeting=await tx.meeting.findFirst({where:{id:meetingId,archivedAt:null},select:{id:true}});if(!meeting)throw this.notFound(ErrorCodes.MEETING_NOT_FOUND,'Meeting not found');const sequence=dto.sequence??((await tx.meetingAgendaItem.aggregate({where:{meetingId,archivedAt:null},_max:{sequence:true}}))._max.sequence??-1)+1;return tx.meetingAgendaItem.create({data:{meetingId,title:dto.title,description:dto.description,sequence}})}
  async createMinutesDocument(id:string){return this.prisma.$transaction(async tx=>{await tx.$executeRaw(Prisma.sql`SELECT pg_advisory_xact_lock(hashtext(${`rd-manager-workbench:meeting-minutes:${id}`}))`);const meeting=await tx.meeting.findFirst({where:{id,archivedAt:null}});if(!meeting)throw this.notFound(ErrorCodes.MEETING_NOT_FOUND,'Meeting not found');if(meeting.minutesDocumentId){const linked=await tx.contentDocument.findUnique({where:{id:meeting.minutesDocumentId}});if(linked)return linked;}const existing=await tx.contentDocument.findFirst({where:{meetingId:id,type:ContentDocumentType.MEETING_MINUTES},orderBy:{createdAt:'asc'}});if(existing){await tx.meeting.update({where:{id},data:{minutesDocumentId:existing.id}});return existing;}const document=await tx.contentDocument.create({data:{type:ContentDocumentType.MEETING_MINUTES,title:`${meeting.title} 会议纪要`,content:meetingMinutesTemplate(meeting.minutes),plainText:meetingMinutesPlainText(meeting.minutes),meetingId:id,projectId:meeting.projectId}});await tx.meeting.update({where:{id},data:{minutesDocumentId:document.id}});return document;});}
  async createTaskForAction(id:string,input:CreateSourceTaskDto){return this.prisma.$transaction(async tx=>{await tx.$executeRaw(Prisma.sql`SELECT pg_advisory_xact_lock(hashtext(${`rd-manager-workbench:meeting-action-task:${id}`}))`);const action=await tx.meetingAction.findFirst({where:{id,archivedAt:null}});if(!action)throw this.notFound(ErrorCodes.MEETING_ACTION_NOT_FOUND,'Meeting action not found');if(action.taskId)return{task:await this.findExistingActionTask(tx,action.taskId),alreadyExists:true};const task=await this.tasks.createTaskInTransaction(tx,{...input,projectId:input.projectId,sourceType:'MEETING_ACTION',sourceId:action.id});const linked=await tx.meetingAction.updateMany({where:{id,taskId:null},data:{taskId:task.id}});if(linked.count)return{task,alreadyExists:false};const current=await tx.meetingAction.findUnique({where:{id},select:{taskId:true}});if(!current?.taskId)throw new AppError({code:ErrorCodes.MEETING_ACTION_TASK_EXISTS,message:'Meeting action task could not be linked',statusCode:HttpStatus.CONFLICT});return{task:await this.findExistingActionTask(tx,current.taskId),alreadyExists:true};});}
  private async findExistingActionTask(tx:Prisma.TransactionClient,taskId:string){const task=await tx.workTask.findUnique({where:{id:taskId},include:{dependencies:{select:{dependsOnTaskId:true}},reminder:true,later:true}});if(!task)throw this.notFound(ErrorCodes.TASK_NOT_FOUND,'Task not found');const{dependencies,...fields}=task;return{...fields,dependencyIds:dependencies.map(({dependsOnTaskId})=>dependsOnTaskId)};}
  private async assertProject(id:string){const project=await this.prisma.project.findFirst({where:{id,archivedAt:null}});if(!project)throw this.notFound(ErrorCodes.PROJECT_NOT_FOUND,'Project not found')}
  private taskStatusFromAction(status:MeetingActionStatus):TaskStatus{if(status===MeetingActionStatus.DONE)return TaskStatus.DONE;if(status===MeetingActionStatus.CANCELLED)return TaskStatus.CANCELLED;if(status===MeetingActionStatus.IN_PROGRESS)return TaskStatus.IN_PROGRESS;return TaskStatus.TODO;}
  private notFound(code:(typeof ErrorCodes)[keyof typeof ErrorCodes],message:string){return new AppError({code,message,statusCode:HttpStatus.NOT_FOUND});}
}
