import { HttpStatus, Injectable } from '@nestjs/common';
import { Prisma } from '@prisma/client';
import { PlatformPrismaService } from '../../../../infrastructure/prisma/platform-prisma.service';
import { AppError } from '../../../../shared/errors/app-error';
import { ErrorCodes } from '../../../../shared/errors/error-codes';
import { TasksService } from '../../tasks/application/tasks.service';
import { CreateCommunicationDto, CreatePartnerAgreementDto, CreatePartnerContactDto, CreatePartnerDto, CreateSourceTaskDto, ListCommunicationsQueryDto, PageQueryDto, UpdateCommunicationDto, UpdatePartnerAgreementDto, UpdatePartnerContactDto, UpdatePartnerDto } from '../interface/http/dto/management.dto';

@Injectable()
export class PartnersService {
  constructor(private readonly prisma: PlatformPrismaService, private readonly tasks: TasksService) {}
  async list(query:PageQueryDto){const page=query.page??1,pageSize=Math.min(query.pageSize??20,100);const where={archivedAt:null};const[data,total]=await this.prisma.$transaction([this.prisma.partner.findMany({where,orderBy:[{updatedAt:'desc'},{id:'desc'}],skip:(page-1)*pageSize,take:pageSize}),this.prisma.partner.count({where})]);return{data,meta:{page,pageSize,total}};}
  async get(id:string){const entity=await this.prisma.partner.findFirst({where:{id,archivedAt:null},include:{contacts:{where:{archivedAt:null},orderBy:{updatedAt:'desc'}},agreements:{where:{archivedAt:null},orderBy:{updatedAt:'desc'}},communications:{where:{archivedAt:null},orderBy:{occurredAt:'desc'}}}});if(!entity)throw this.notFound(ErrorCodes.PARTNER_NOT_FOUND,'Partner not found');return entity;}
  async create(dto:CreatePartnerDto){return this.prisma.partner.create({data:dto});}
  async update(id:string,dto:UpdatePartnerDto){const result=await this.prisma.partner.updateMany({where:{id,archivedAt:null},data:dto});if(!result.count)throw this.notFound(ErrorCodes.PARTNER_NOT_FOUND,'Partner not found');return this.get(id);}
  async archive(id:string){return this.prisma.$transaction(async tx=>{const partner=await tx.partner.findFirst({where:{id,archivedAt:null}});if(!partner)throw this.notFound(ErrorCodes.PARTNER_NOT_FOUND,'Partner not found');const [contacts,agreements,communications]=await Promise.all([tx.partnerContact.count({where:{partnerId:id,archivedAt:null}}),tx.partnerAgreement.count({where:{partnerId:id,archivedAt:null}}),tx.communicationRecord.count({where:{partnerId:id,archivedAt:null}})]);if(contacts+agreements+communications)throw new AppError({code:ErrorCodes.PARTNER_HAS_ACTIVE_RECORDS,message:'Partner has active related records',statusCode:HttpStatus.CONFLICT});await tx.partner.update({where:{id},data:{archivedAt:new Date()}});});}
  async createContact(partnerId:string,dto:CreatePartnerContactDto){await this.get(partnerId);return this.prisma.partnerContact.create({data:{partnerId,...dto}})}
  async updateContact(partnerId:string,id:string,dto:UpdatePartnerContactDto){return this.updateChild('partnerContact',partnerId,id,dto,ErrorCodes.PARTNER_CONTACT_NOT_FOUND)}
  async archiveContact(partnerId:string,id:string){await this.archiveChild('partnerContact',partnerId,id,ErrorCodes.PARTNER_CONTACT_NOT_FOUND)}
  async createAgreement(partnerId:string,dto:CreatePartnerAgreementDto){await this.get(partnerId);return this.prisma.partnerAgreement.create({data:{partnerId,...dto,startAt:dto.startAt?new Date(dto.startAt):undefined,endAt:dto.endAt?new Date(dto.endAt):undefined}})}
  async updateAgreement(partnerId:string,id:string,dto:UpdatePartnerAgreementDto){return this.updateChild('partnerAgreement',partnerId,id,{...dto,startAt:dto.startAt?new Date(dto.startAt):undefined,endAt:dto.endAt?new Date(dto.endAt):undefined},ErrorCodes.PARTNER_AGREEMENT_NOT_FOUND)}
  async archiveAgreement(partnerId:string,id:string){await this.archiveChild('partnerAgreement',partnerId,id,ErrorCodes.PARTNER_AGREEMENT_NOT_FOUND)}
  async listCommunications(partnerId:string,query:ListCommunicationsQueryDto){await this.get(partnerId);const page=query.page??1,pageSize=Math.min(query.pageSize??20,100);const where:Prisma.CommunicationRecordWhereInput={partnerId,archivedAt:null,...(query.nextFollowUpBefore?{nextFollowUpAt:{lte:new Date(query.nextFollowUpBefore)}}:{})};const[data,total]=await this.prisma.$transaction([this.prisma.communicationRecord.findMany({where,orderBy:[{occurredAt:'desc'}],skip:(page-1)*pageSize,take:pageSize}),this.prisma.communicationRecord.count({where})]);return{data,meta:{page,pageSize,total}};}
  async createCommunication(partnerId:string,dto:CreateCommunicationDto){return this.prisma.$transaction(async tx=>{const partner=await tx.partner.findFirst({where:{id:partnerId,archivedAt:null}});if(!partner)throw this.notFound(ErrorCodes.PARTNER_NOT_FOUND,'Partner not found');if(dto.contactId){const contact=await tx.partnerContact.findFirst({where:{id:dto.contactId,partnerId,archivedAt:null}});if(!contact)throw this.notFound(ErrorCodes.PARTNER_CONTACT_NOT_FOUND,'Partner contact not found');}if(dto.projectId){const project=await tx.project.findFirst({where:{id:dto.projectId,archivedAt:null}});if(!project)throw this.notFound(ErrorCodes.PROJECT_NOT_FOUND,'Project not found');}return tx.communicationRecord.create({data:{partnerId,...dto,occurredAt:new Date(dto.occurredAt),nextFollowUpAt:dto.nextFollowUpAt?new Date(dto.nextFollowUpAt):undefined}});});}
  async updateCommunication(partnerId:string,id:string,dto:UpdateCommunicationDto){return this.updateChild('communicationRecord',partnerId,id,{...dto,occurredAt:dto.occurredAt?new Date(dto.occurredAt):undefined,nextFollowUpAt:dto.nextFollowUpAt?new Date(dto.nextFollowUpAt):undefined},ErrorCodes.COMMUNICATION_NOT_FOUND)}
  async archiveCommunication(partnerId:string,id:string){await this.archiveChild('communicationRecord',partnerId,id,ErrorCodes.COMMUNICATION_NOT_FOUND)}
  async createTaskForCommunication(id:string,input:CreateSourceTaskDto){return this.prisma.$transaction(async tx=>{const communication=await tx.communicationRecord.findFirst({where:{id,archivedAt:null}});if(!communication)throw this.notFound(ErrorCodes.COMMUNICATION_NOT_FOUND,'Communication not found');return this.tasks.createTaskInTransaction(tx,{...input,projectId:input.projectId??communication.projectId??undefined,sourceType:'COMMUNICATION',sourceId:communication.id});});}
  private async updateChild(delegate:'partnerContact'|'partnerAgreement'|'communicationRecord',partnerId:string,id:string,data:object,code:(typeof ErrorCodes)[keyof typeof ErrorCodes]){const result=await (this.prisma[delegate] as any).updateMany({where:{id,partnerId,archivedAt:null},data});if(!result.count)throw this.notFound(code,'Related record not found');return (this.prisma[delegate] as any).findUnique({where:{id}})}
  private async archiveChild(delegate:'partnerContact'|'partnerAgreement'|'communicationRecord',partnerId:string,id:string,code:(typeof ErrorCodes)[keyof typeof ErrorCodes]){const result=await (this.prisma[delegate] as any).updateMany({where:{id,partnerId,archivedAt:null},data:{archivedAt:new Date()}});if(!result.count)throw this.notFound(code,'Related record not found');}
  private notFound(code:(typeof ErrorCodes)[keyof typeof ErrorCodes],message:string){return new AppError({code,message,statusCode:HttpStatus.NOT_FOUND});}
}
