import { Body, Controller, Delete, Get, HttpCode, HttpStatus, Param, Patch, Post, Query } from '@nestjs/common';
import { PERMISSIONS, RequirePermissions } from '../../../../iam/interface/http/permissions.decorator';
import { MeetingsService } from '../../application/meetings.service';
import { CreateMeetingActionDto, CreateMeetingAgendaItemDto, CreateMeetingDto, CreateSourceTaskDto, ListMeetingsQueryDto, UpdateMeetingActionDto, UpdateMeetingDto } from './dto/management.dto';
@Controller('meetings')
@RequirePermissions(PERMISSIONS.MEETING_READ)
export class MeetingsController {constructor(private readonly service:MeetingsService){} @Get()list(@Query()q:ListMeetingsQueryDto){return this.service.list(q)}@Post()@RequirePermissions(PERMISSIONS.MEETING_CREATE)create(@Body()d:CreateMeetingDto){return this.service.create(d)}@Post(':id/minutes-document')@RequirePermissions(PERMISSIONS.MEETING_UPDATE)minutesDocument(@Param('id')id:string){return this.service.createMinutesDocument(id)}@Get(':id')get(@Param('id')id:string){return this.service.get(id)}@Patch(':id')@RequirePermissions(PERMISSIONS.MEETING_UPDATE)update(@Param('id')id:string,@Body()d:UpdateMeetingDto){return this.service.update(id,d)}@Delete(':id')@HttpCode(HttpStatus.NO_CONTENT)@RequirePermissions(PERMISSIONS.MEETING_DELETE)async archive(@Param('id')id:string){await this.service.archive(id)}@Post(':id/actions')@RequirePermissions(PERMISSIONS.MEETING_UPDATE)action(@Param('id')id:string,@Body()d:CreateMeetingActionDto){return this.service.createAction(id,d)}@Patch(':id/actions/:childId')@RequirePermissions(PERMISSIONS.MEETING_UPDATE)updateAction(@Param('id')id:string,@Param('childId')child:string,@Body()d:UpdateMeetingActionDto){return this.service.updateAction(id,child,d)}@Delete(':id/actions/:childId')@HttpCode(HttpStatus.NO_CONTENT)@RequirePermissions(PERMISSIONS.MEETING_UPDATE)async archiveAction(@Param('id')id:string,@Param('childId')child:string){await this.service.archiveAction(id,child)}@Post(':id/agenda-items')@RequirePermissions(PERMISSIONS.MEETING_UPDATE)agenda(@Param('id')id:string,@Body()d:CreateMeetingAgendaItemDto){return this.service.createAgendaItem(id,d)}}
@Controller('meeting-actions')
@RequirePermissions(PERMISSIONS.MEETING_READ)
export class MeetingActionsController {constructor(private readonly service:MeetingsService){}@Post(':id/task')@RequirePermissions(PERMISSIONS.TASK_CREATE)task(@Param('id')id:string,@Body()d:CreateSourceTaskDto){return this.service.createTaskForAction(id,d)}}
