/** Centralised route path constants. Use these everywhere instead of raw strings. */
export const ROUTES = {
  LOGIN: '/login',
  CHANGE_PASSWORD: '/change-password',
  FORBIDDEN: '/forbidden',
  PERSONAL_SECURITY: '/settings/security',
  ADMIN: '/admin',
  ADMIN_USERS: '/admin/users',
  ADMIN_ROLES: '/admin/roles',
  ADMIN_PERMISSIONS: '/admin/permissions',
  ADMIN_AUDITS: '/admin/security-audits',
  ADMIN_OWNERSHIP_MIGRATION: '/admin/ownership-migration',
  HOME: '/',
  MY_WORK: '/my-work',
  PROJECT_SPACES: '/spaces/projects',
  projectWorkspace: (projectId: string, section = 'overview') =>
    `/spaces/projects/${encodeURIComponent(projectId)}/${section}`,
  EMPLOYEES: '/employees',
  employeeDetail: (employeeId: string) => `/employees/${encodeURIComponent(employeeId)}`,
  DOCS: '/docs',
  BASE: '/base',
  CALENDAR: '/calendar',
  SEARCH: '/search',

  // Compatibility paths remain reachable outside the primary navigation.
  LIBRARY: '/library',
  APPLICATIONS: '/library/applications',
  governance: (kind: string) => `/library/governance/${kind}`,
  MEETINGS: '/meetings',
  KNOWLEDGE: '/knowledge',
  AUTOMATION_DATA: '/automation-data',
  SETTINGS: '/settings',
  DATA_GOVERNANCE: '/settings/data-governance',
  EXTENSIONS_SETTINGS: '/settings/extensions',
  OPERATIONS: '/library/operations',
  RESOURCES: '/library/operations?tab=resources',
  RESOURCES_LEGACY: '/resources',
  REPORTS: '/library/reports',
  INTELLIGENCE: '/library/intelligence',
  INTELLIGENCE_BRIEFS: '/library/intelligence/briefs',

  // Legacy paths remain available for redirects until bookmarks have migrated.
  PROJECTS: '/projects',
  TASKS: '/tasks',
  APPLICATION_CASES: '/application-cases',
  RISKS: '/risks',
  ISSUES: '/issues',
  DECISIONS: '/decisions',
  PARTNERS: '/partners',
}
